# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 4
palette:
  white: "#FFFFFF"
  path: "#67f570"
  success: "#44e3d0"
  error: "#ff6347"
  git: "#ffa500"
  session: "#ffffff"
  cmd: "#f2f567"
blocks:
  - type: "prompt"
    alignment: "left"
    segments:
      - type: "status"
        foreground: "p:success"
        foreground_templates:
          - "{{ if gt .Code 0 }}p:error{{ end }}"
        options:
          always_enabled: true
        style: "plain"
        template: " [{{ if gt .Code 0 }}\uf00d {{ reason .Code }}{{ else }}\uf00c{{ end }}]"
      - type: "path"
        foreground: "p:path"
        options:
          style: "full"
        style: "plain"
        template: "[{{ .Path }}]"
      - type: "git"
        foreground: "p:git"
        options:
          fetch_upstream_icon: true
        style: "plain"
        template: "[{{ .HEAD }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }}]"
  - type: "prompt"
    alignment: "left"
    newline: true
    segments:
      - type: "session"
        style: "plain"
        foreground: "p:session"
        template: " {{ .UserName }}@{{ .HostName}} "
      - type: "text"
        template: "\u279c"
        foreground: "p:cmd"
        style: "plain"
